USE [master]
GO

/****** Object:  Database [Pho]    Script Date: 12/11/2017 3:16:49 PM ******/
CREATE DATABASE [Pho]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Pho', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SHACOJX\MSSQL\DATA\Pho.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Pho_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SHACOJX\MSSQL\DATA\Pho_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Pho] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Pho].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Pho] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Pho] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Pho] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Pho] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Pho] SET ARITHABORT OFF 
GO

ALTER DATABASE [Pho] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Pho] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Pho] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Pho] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Pho] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Pho] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Pho] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Pho] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Pho] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Pho] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Pho] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Pho] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Pho] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Pho] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Pho] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Pho] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Pho] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Pho] SET RECOVERY FULL 
GO

ALTER DATABASE [Pho] SET  MULTI_USER 
GO

ALTER DATABASE [Pho] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Pho] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Pho] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Pho] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Pho] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Pho] SET  READ_WRITE 
GO

